config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

#change_admin_group
#delete_admin_group

resources :gmanagers

app/models/gmanager.rb
class Gmanager < ActiveRecord::Base
  unloadable
  
  #show all project groups
  #returns hash {id_group => [array of users in group]}
  def self.getAll(pr_id)
    pr_id = pr_id.to_s
    pid = Project.find_by_identifier(pr_id).id
    mem = Member.where(:project_id => pid).order(user_id: :asc)
    res = { }
    for m in mem
      begin
        gr = Group.find(m.user_id)
        users = User.in_group(m.user_id)
        res[m.user_id] = users
        rescue
        #if not group go next by loop
           next
      end
    end
    return res
  end

  #return group owner's id (user id) if exists
  #idgr - ID of searchable group
  def self.get_group_owner(idgr)
    res = Gmanager.find_by_id_group(idgr)
    res = (res.blank?) ? false : res['id_owner']
    res  
  end
  
  #return user custom field names or an empty array if none are available
  def self.get_user_cf_keys()
    keys = CustomField.where(:type => 'UserCustomField')
    res = []
    if !keys.blank?
      i = 0
      keys.each do |c|
        res[i] = c['name']
        i += 1
      end	
    end
    res
  end
  
  #return user custom field values or an empty array if none are available
  def self.get_user_cf_values(id)
    keys = CustomField.where(:type => 'UserCustomField')
    values = User.find(id).custom_values

    res = []
    if !keys.blank?
      i = 0
      keys.each do |c|
        res[i] = values[i] ? values[i][:value].to_s : "-"
        i += 1
      end	
    end
    res
    #res = { }
    #res[:pos] = val[0] ? val[0][:value].to_s : "-"
    #res[:dep] = val[1] ? val[1][:value].to_s : "-"
    #res
  end

  def self.get_group_name_by_id(id)
    Group.find(id).lastname
  end

  def self.get_group_users(id)
    id = id.to_s
    User.in_group(id)
  end

  #get all users exept group's
  def self.get_all_project_users(id,grid)
    id = id.to_s
    pid = Project.find_by_identifier(id).id
    tres = []
    mem = Member.where(:project_id => pid).to_a
    mem.delete_if{|x| x.user_id==grid}
    mcount = mem.count
    for i in 0..mcount-1
      begin
        user = User.find(mem[i]['user_id'])
        tres.push(user)
      rescue
        tres.concat(User.in_group(mem[i]['user_id']))
        tres.uniq!
      end
    end
  #Fucking dump piecae of code cose index not working    
    gusers = User.in_group(grid)
    temp = []
    gusers.each do |i|
      temp.push(i["id"])
    end
    res = { }
    tres.each do |t|
      if !temp.index(t["id"])
        res[t["id"]] = t["lastname"].to_s + " " + t["firstname"].to_s
      end
    end
    res
  end

  def self.update_name(idgr,name)
    begin
      gr = Group.find(idgr)
      res = gr.update_attributes(:lastname => name.to_s)
      return res
    rescue
      return 0
    end
  end

  def self.delete_user_from_group(idus,idgr)
    gr=Group.find(idgr)
    us=User.find(idus)
    gr.users.delete(us)
    gr.save
  end

  #MAKE check what are you send to db
  #idpr - identifier of project (letter)
  #name - name of group
  #owner - id of user, who create group
  def self.create_group(idpr,name,owner)
    #check the unique of name
    if Group.find_by_lastname(name).blank?    
      gr = Group.create(:lastname => name)
      pid = Project.find_by_identifier(idpr).id
      mem = Member.new(:project_id => pid, :user_id => gr.id) 
      mem.role_ids = [6]
      mem.save 
      Project.find(pid).members << mem
      #create entry in gmanagers table
      gm = Gmanager.create(:id_group => gr.id, :id_owner => owner)
      gm.save
      return true
    else
      return false
    end
end

  #idpr - identifier of project
  #idgr - ID of deleted group
  #iduser - Id of user who wants to delete group
  def self.delete_group(idpr,idgr)
    pgm = Gmanager.find_by_id_group(idgr)
    pid = Project.find_by_identifier(idpr.to_s).id
    idm = Member.find_by_project_id_and_user_id(pid, idgr)
    Member.delete(idm)
    Group.delete(idgr)
    if not pgm.blank?
      Gmanager.delete(pgm)
    end
  end

  #check if user have enough rights to do action to group
  #return bool
  #id_project-identifier of project (not ID)..
  #id_user- ID user
  #action -  desired action (symbol!)
  def self.may_user_do(id_project,id_user,action)
    project = Project.find_by_identifier(id_project)
    user = User.find(id_user)
    roles = user.roles_for_project(project)
    for r in roles
      if r[:permissions].include?(action)
        return true
      end
    end
    return false
  end

  #check if user is owner of the group
  #iduser, idgr - IDs, string
  def self.is_owner(idgr, iduser)
    if Gmanager.find_by_id_group_and_id_owner(idgr, iduser).blank?
      return false
    else
      return true
    end
  end

  #search in Gmanager, if there is no entry - group is admin group
  def self.is_admin_group(idgr)
    if Gmanager.find_by_id_group(idgr).blank?
      return true
    else
      return false
    end
  end

  def self.get_user_name(iduser)
    if iduser
      res = User.find(iduser)
      ret = res['lastname'].to_s + " " + res['firstname'].to_s
      return ret
    else
      return false
    end
  end


  #insert into Gmanager table new entry or change existing
  def self.change_owner(id_group, id_owner)
    gm = Gmanager.find_by_id_group(id_group)
    if gm.blank?
      gm=Gmanager.create(:id_group => id_group, :id_owner => id_owner)
    else
      gm.update_attribute(:id_owner, id_owner)
    end
    gm.save
  end

end

app/controllers/gmanagers_controller.rb
#!/bin/env ruby
# encoding: utf-8
class GmanagersController < ApplicationController
  unloadable

  before_filter :find_project, :authorize

  def find_project
    @project=Project.find(params["project_id"])
  end
    
  def index
    @project = Project.find(params[:project_id])
    @groups = Gmanager.getAll(params[:project_id])
  end
  
  def create
    error = ''
    if Gmanager.create_group(params["project_id"], params["groupname"], session['user_id'])
      error = "Group with the same name already exists"
    end 
    respond_to do |format|
      format.html { redirect_to gmanagers_path(:project_id => @project, :error => error) }
    end
  end

  def new
    @project = Project.find(params[:project_id])
  end
  
  def show
    @project = Project.find(params[:project_id])
    #only one group not all of them
    @group = Gmanager.get_group_users(params["id"])
  end
  
  def edit
    @project = Project.find(params[:project_id])
    @group = Gmanager.get_group_users(params["id"])
 
    @all_users = Gmanager.get_all_project_users(params[:project_id], params["id"])
  end

  def update
    @project = params['project_id']
    @group = Group.find(params["id"])
    temp = params["edit"]
    
    #render error if user try to change something without permissions
    if (Gmanager.is_admin_group(params["id"]) and not Gmanager.may_user_do(params['project_id'], session["user_id"], :change_admin_groups)) or (not Gmanager.is_owner(params["id"], session["user_id"]) and not Gmanager.may_user_do(params["project_id"], session["user_id"], :change_other_groups)) 
	respond_to do |format|
	    format.html { redirect_to gmanagers_path(:project_id => @project, :error => "You've got no rights for managing this group") and return }
	end
    end

    case temp
    when "group_name"
      res=Gmanager.update_name(params["id"], params["groupname"])
      if res
        respond_to do |format|
	  format.html { redirect_to edit_gmanager_path(:project_id => @project, :id => params["id"]) }
	end
      else
	respond_to do |format|
          #format.html {render :action => "edit", :error=>"Группа с таким именем уже существут"}
          format.html { redirect_to gmanagers_path(:project_id => @project, :error => "Group with the same name already exists") }
	end
    end
    when "add_user"
      if params["user_select"]
	users = User.where(:id => params["user_select"])
	@group.users << users
	respond_to do |format|
          format.html { redirect_to edit_gmanager_path(:project_id => @project, :id => params["id"]) }
	end
      else
	respond_to do |format|
          format.html { redirect_to edit_gmanager_path(:project_id => @project, :id => params["id"], :error => "You must choose users to add") }
	end

      end
    when "del_user"
      #@group.users.delete(User.find(params["user"]))
      Gmanager.delete_user_from_group(params["user"], params["group"])
      respond_to do |format|
        format.html { redirect_to edit_gmanager_path(:project_id => @project, :id => params["group"]) }
      end
	    
    when "change_owner"
      if Gmanager.may_user_do(params['project_id'],session['user_id'],:change_owner)
	Gmanager.change_owner(params['id'],params['owner'])
	respond_to do |format|
          format.html { redirect_to edit_gmanager_path(:project_id=>@project,:id=>params["id"]) }
	end
      end
	
    end
  end
  
#empty controllers action
  def update_admin
    
  end
#empty controllers action
  def delete_admin
  
  end

  def destroy
    @project = Project.find(params[:project_id])
    
    #check if user try to change admin created group
    if Gmanager.is_admin_group(params["id"]) and not Gmanager.may_user_do(@project,session["user_id"], :delete_admin_groups) or not Gmanager.is_owner(params["id"],session["user_id"]) and not Gmanager.may_user_do(@project,session["user_id"], :delete_other_groups) 
      respond_to do |format|
        format.html { redirect_to gmanagers_path(:project_id => @project, :error => "You have not enough rights to delete this group") and return }
      end
    end
    
    Gmanager.delete_group(params["project_id"], params["id"])
    respond_to do |format|
      format.html { redirect_to gmanagers_path(:project_id => @project) }
    end
  end
end

app/helpers/gmanagers_helper.rb
module GmanagersHelper

  def link_to_group(id)
    name = Gmanager.get_group_name_by_id(id)
    return link_to name, gmanager_path(id, :project_id => params[:project_id])
  end

  def render_group_by_id(id)
    return Gmanager.get_group_name_by_id(id)
  end

  def render_cf_keys()
    return Gmanager.get_user_cf_keys()
  end

  def render_cf_values(id)
    return Gmanager.get_user_cf_values(id)
  end

  def render_group_owner(idgr)
    id = Gmanager.get_group_owner(idgr)
    return id
  end

  def render_user_name(id)
    ret =  Gmanager.get_user_name(id)    
    if not ret
      return Gmanager.get_user_name(User.current.id)
    else
      return ret
    end
  end

  def render_possible_owners()
    users = User.all
    ret = []
    for u in users
      ret.append([u['firstname'].to_s + " " + u['lastname'].to_s, u['id']])
    end
    return ret
  end

end

app/views/gmanagers/destroy.html.erb
<h2>GmanagersController#delete</h2>

app/views/gmanagers/edit.html.erb
<h2><%= link_to "Groups",gmanagers_path(:project_id=>params["project_id"]) %> >> <%= link_to render_group_by_id(params["id"].to_i),gmanager_path(params[:id],:project_id=>params["project_id"]) %> </h2>


<div class="splitcontentleft">

<%= form_tag gmanager_path(params["id"],:edit=>"group_name",:project_id=>params["project_id"]), :method=>"put", :class=>"edit_group" do %>
<fieldset>
<p>
<label> Group name <%= text_field_tag "groupname",render_group_by_id(params["id"].to_i) %></label>  <%= submit_tag l(:button_save)%>
</p>
<%= params["error"] %>
</fieldset>
<% end %>

<% if  Gmanager.may_user_do(params['project_id'],session['user_id'],:change_owner)  %>
<fieldset>
<%= form_tag gmanager_path(:edit=>"change_owner",:project_id=>params["project_id"]),:id=>params["id"], :method=>"put", :class=>"edit_groups" do %>

<p>

<label> Owner</label> <%=  select_tag(:owner, options_for_select(render_possible_owners(),render_group_owner(params["id"]) ))%>
 <%= submit_tag l(:button_save) %>
</p>


<% end %>
</fieldset>

<%  end   %>


<div class="tab-content" >
<table class="list users">
<thead><tr>
      <th>Users</th>
      <th style="width:15%"></th>
    </tr></thead>
<tbody>

<% for u in @group%>
<tr> 
<td> <%= u["lastname"].to_s + " " + u["firstname"].to_s %> </td>
<td> <%= link_to "delete",gmanager_path(:group=>params["id"],:user=>u["id"],:edit=>"del_user",:project_id=>params["project_id"]), :method=>"put", :class=>"icon icon-del" %> </td>
</tr>
<% end %>

</tbody>
</table>
</div>

</div>



<div class="splitcontentright">

<div id="users">
<%= form_tag gmanager_path(params["id"],:edit=>"add_user",:project_id=>params["project_id"]), :method=>"put", :class=>"edit_group" do%>

<fieldset style="width: 40%">
<div id="users">
<% for k,v in @all_users %>
<p><label> <%= check_box_tag 'user_select[]',k %> <%= v %> </label></p>
<% end %>
</div>
</fieldset>
<p>
<%= submit_tag l(:button_add)%>
</p>
<% end %>

</div>

</div>

app/views/gmanagers/index.html.erb
<h2>Current project groups</h2>



<div class="splitcontentleft">
<table class="list groups">
<thead>
<th> Groups </th>
<th> Users </th>
<th> Owner </th>
<th> </th>
</thead>

<tbody>
<% for k,v in @groups %>
<tr>

<td><%= link_to_group(k) %></td>
<td> <%= v.count %> </td>
<td> <%= render_user_name(render_group_owner(k)) %>  </td>
<td class="button"> <%= link_to "Delete",{:controller=>"gmanagers", :action=>"destroy",:id=>k,:project_id=>params["project_id"]}, :method=>"delete", :confirm=>"Are you sure?",:class=>"icon icon-del"%></td>

</tr>
<% end %>
</tbody>
</table>

<div class="error"><label class="error"><%= params['error'] %></label></div>
<br>


<br>
<%= link_to "Create group",new_gmanager_path(:project_id=>params["project_id"]), :class => "icon icon-add" %>
</div>

app/views/gmanagers/new.html.erb
<h2>Group add</h2>
<label> Name of group <%= form_tag gmanagers_path(:project_id=>@project), :method=>"post" do%></label>
<%= text_field_tag "groupname" %>

<%= submit_tag l(:button_save)%>
<% end %>

app/views/gmanagers/show.html.erb
<h2><%= link_to "Groups",gmanagers_path(:project_id=>params["project_id"])%> &gt;&gt; <%= render_group_by_id(params["id"].to_i) %></h2>
<div class="tab-content" id="tab-content-general">
  <div class="splitcontentleft">
    <table class="group list">
      <thead>
        <tr>
          <th class="label"><label class="user" value="user">User</label></th> 
          <% for cf_key in render_cf_keys() %>
            <th><%= cf_key %></th> 
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% for u in @group %>
          <tr>
            <td class="user"><%= u["lastname"].to_s + " " + u["firstname"].to_s %></td>
            <% for cf_value in render_cf_values(u["id"].to_i) %>
              <td><%= cf_value %></td> 
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to "Change", edit_gmanager_path(params["id"], :project_id=>params["project_id"]) %>
  </div>
</div>

app/views/gmanagers/update.html.erb
<h2>GmanagersController#update</h2>
<%= params %>
<br>
group:
<%= @group %>
<br>
DEBUG
<br>
<%= @debugg %>